modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="plagatesummon"
version="${file.jarVersion}"
displayName="Random Gateways Spawning"
logoFile="examplemod.png" #optional
credits="Thanks for this example mod goes to Java"
authors="pla_is_me"
description='''
Pla made this mod for randomly summon gates.
'''
[[dependencies.plagatesummon]]
modId="minecraft"
mandatory=true
versionRange="[1.18.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.plagatesummon]]
modId="forge"
mandatory=true
versionRange="[40.2.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.plagatesummon]]
modId="ftbchunks"
mandatory=true
versionRange="[1802.3.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.plagatesummon]]
modId="gateways"
mandatory=true
versionRange="[2.3.0,)"
ordering="AFTER"
side="BOTH"
